version: '3.4'

services:
    db:
        container_name: mysqlc
        hostname: mysqlc
        image: mysql:latest
        restart: always
        # networks:
        #    milescarrentalnetwork:
        #         #ipv4_address: 10.130.2.130
        ports:
        - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'milescarrental'
            MYSQL_USER: 'umilescarrental'
            MYSQL_PASSWORD: 'pmilescarrental'
        volumes:
        - /var/lib/mysql 

    # milescarrental.api:
    #     image: ${DOCKER_REGISTRY-}milescarrentalapi
    #     build:
    #         context: .
    #         dockerfile: MilesCarRental.Api/Dockerfile
    #     ports:
    #         - '56638:80'
    #         - '56639:443'  
        # depends_on:
        #   - db

# networks:
#     milescarrentalnetwork:
#         driver: bridge
    # default:
    #     external: true
    #     name: microservicemilescarrental
