version: '3.4'

services:
    db:
        image: mysql:latest
        restart: always
        ports:
        - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'milescarrental'
            MYSQL_USER: 'umilescarrental'
            MYSQL_PASSWORD: 'pmilescarrental'
        volumes:
        - /var/lib/mysql

    milescarrental.api:
        image: ${DOCKER_REGISTRY-}milescarrentalapi
        build:
            context: .
            dockerfile: MilesCarRental.Api/Dockerfile

